addLayer("a", {
    name: "The Galactic Survey",
    startData() { return { unlocked: true, points: new Decimal(0) } },
    color: "#ffe082",
    resource: "survey badges",
    row: "side",
    symbol: "A",
    tooltip() { return "The Galactic Survey" },
    achievementPopups: true,
    tabFormat: [
        "main-display",
        ["display-text", function() { return 'Survey badges earned: <b>' + formatWhole(player.a.achievements.length) + '</b> / 60' }],
        ["display-text", function() {
            let survey = new Decimal(1)
            for (let i = 10; i <= 69; i++) if (hasAchievement("a", i)) survey = survey.times(achievementEffect("a", i))
            return 'Survey bonus to stardust gain: <b>×' + format(survey.max(1).pow(0.25).min(1e6)) + '</b> (all 60 goals are compressed to a 0.25 power so this side track can never outgrow the main ladder)'
        }],
        ["blank", "12px"],
        "achievements",
    ],
    update() {
        if (hasAchievement("a", 20) && !hasMilestone("or1", 0)) player.or1.milestones.push(0)
        if (hasAchievement("a", 21) && !hasMilestone("pe1", 1)) player.pe1.milestones.push(1)
        if (hasAchievement("a", 22) && !hasMilestone("sg1", 0)) player.sg1.milestones.push(0)
        if (hasAchievement("a", 23) && !hasMilestone("oa1", 1)) player.oa1.milestones.push(1)
        if (hasAchievement("a", 30) && !hasMilestone("or6", 1)) player.or6.milestones.push(1)
        if (hasAchievement("a", 38) && !hasMilestone("or11", 1)) player.or11.milestones.push(1)
        if (hasAchievement("a", 39) && !hasMilestone("or16", 1)) player.or16.milestones.push(1)
    },
    achievements: {
        10: { name: "First Breath",
            done() { return player.points.gte(10) },
            tooltip: "Have 10 stardust.<br>Reward: stardust ×2",
            effect() { return new Decimal(2) },
        },
        11: { name: "Cloud Seeding",
            done() { return player.gc.points.gte(1) },
            tooltip: "Collapse your first gas clouds.<br>Reward: stardust ×2",
            effect() { return new Decimal(2) },
        },
        12: { name: "Ignition",
            done() { return player.ps.ignitions >= 1 },
            tooltip: "Ignite the protostar once.<br>Reward: stardust ×2",
            effect() { return new Decimal(2) },
        },
        13: { name: "Let There Be Light",
            done() { return player.fu.points.gte(1) },
            tooltip: "Gain fusion plasma.<br>Reward: stardust ×2",
            effect() { return new Decimal(2) },
        },
        14: { name: "Worlds Without End",
            done() { return player.pl.points.gte(1) },
            tooltip: "Accrete a planetary system.<br>Reward: stardust ×2",
            effect() { return new Decimal(2) },
        },
        15: { name: "Fourfold Sky",
            done() { return player.or1.unlocked && player.pe1.unlocked && player.sg1.unlocked && player.oa1.unlocked },
            tooltip: "Unlock all four arms.<br>Reward: stardust ×3",
            effect() { return new Decimal(3) },
        },
        16: { name: "Century Club",
            done() { return player.gc.best.gte(100) },
            tooltip: "Hold 100 gas clouds at once.<br>Reward: stardust ×2",
            effect() { return new Decimal(2) },
        },
        17: { name: "Serial Igniter",
            done() { return player.ps.ignitions >= 25 },
            tooltip: "Ignite the protostar 25 times.<br>Reward: stardust ×3",
            effect() { return new Decimal(3) },
        },
        18: { name: "Chandrasekhar",
            done() { return player.or5.best.gte(1.44) },
            tooltip: "Fill a white dwarf to its absolute limit.<br>Reward: bragging rights",
            effect() { return new Decimal(1) },
        },
        19: { name: "Total Ionization",
            done() { return player.pe3.best.gte(100) },
            tooltip: "Ionize an HII region to 100%.<br>Reward: bragging rights",
            effect() { return new Decimal(1) },
        },
        20: { name: "Stellar Graduation",
            done() { return player.or2.unlocked },
            tooltip: "Reach row 2 of the Orion Arm.<br>Reward: a milestone granted",
            effect() { return new Decimal(1) },
        },
        21: { name: "Cluster Hopper",
            done() { return player.pe2.unlocked },
            tooltip: "Reach row 2 of the Perseus Arm.<br>Reward: a milestone granted",
            effect() { return new Decimal(1) },
        },
        22: { name: "Dark Record",
            done() { return player.sg2.unlocked },
            tooltip: "Reach row 2 of the Sagittarius Arm.<br>Reward: a milestone granted",
            effect() { return new Decimal(1) },
        },
        23: { name: "Transient Hunter",
            done() { return player.oa2.unlocked },
            tooltip: "Reach row 2 of the Outer Arm.<br>Reward: a milestone granted",
            effect() { return new Decimal(1) },
        },
        24: { name: "Gas Tycoon",
            done() { return player.gc.points.gte("1e6") },
            tooltip: "Hold 1e6 gas clouds.<br>Reward: stardust ×5",
            effect() { return new Decimal(5) },
        },
        25: { name: "Plasma Forge",
            done() { return player.fu.points.gte("1e5") },
            tooltip: "Hold 1e5 fusion plasma.<br>Reward: stardust ×5",
            effect() { return new Decimal(5) },
        },
        26: { name: "Orrery Complete",
            done() { return getBuyableAmount("pl", 11).gte(10) },
            tooltip: "Buy 10 Resonance Forge levels.<br>Reward: stardust ×5",
            effect() { return new Decimal(5) },
        },
        27: { name: "Trialist",
            done() { return hasChallenge("oa6", 11) },
            tooltip: "Complete your first Supernova Trial.<br>Reward: stardust ×5",
            effect() { return new Decimal(5) },
        },
        28: { name: "Octa-Trial",
            done() { return ["11","12","13","14","21","22","23","24"].every(c => hasChallenge("oa6", c)) },
            tooltip: "Complete all eight Supernova Trials.<br>Reward: stardust ×25",
            effect() { return new Decimal(25) },
        },
        29: { name: "WIMP Whisperer",
            done() { return player.sg20.hits >= 5 },
            tooltip: "Detect 5 WIMP recoils.<br>Reward: bragging rights",
            effect() { return new Decimal(1) },
        },
        30: { name: "Galactic Era",
            done() { return player.or6.unlocked },
            tooltip: "Enter the Galactic Era (row 6).<br>Reward: passive generation granted",
            effect() { return new Decimal(1) },
        },
        31: { name: "Static Tension",
            done() { return player.sg6.points.gte(5) },
            tooltip: "Buy 5 floors of a Galactic Era layer.<br>Reward: stardust ×10",
            effect() { return new Decimal(10) },
        },
        32: { name: "Heavy Metal",
            done() { return player.or7.heavy.gte("1e6") },
            tooltip: "Accumulate 1e6 heavy elements.<br>Reward: stardust ×10",
            effect() { return new Decimal(10) },
        },
        33: { name: "Dark Ledger",
            done() { return player.dm.darkMatter.gte("1e6") },
            tooltip: "Accumulate 1e6 dark matter.<br>Reward: stardust ×10",
            effect() { return new Decimal(10) },
        },
        34: { name: "Arm Completer",
            done() { return player.or22.unlocked },
            tooltip: "Take the Orion Arm to its final row.<br>Reward: stardust ×25",
            effect() { return new Decimal(25) },
        },
        35: { name: "Gas Completer",
            done() { return player.pe22.unlocked },
            tooltip: "Take the Perseus Arm to its final row.<br>Reward: stardust ×25",
            effect() { return new Decimal(25) },
        },
        36: { name: "Dark Completer",
            done() { return player.sg22.unlocked },
            tooltip: "Take the Sagittarius Arm to its final row.<br>Reward: stardust ×25",
            effect() { return new Decimal(25) },
        },
        37: { name: "Transient Completer",
            done() { return player.oa22.unlocked },
            tooltip: "Take the Outer Arm to its final row.<br>Reward: stardust ×25",
            effect() { return new Decimal(25) },
        },
        38: { name: "Cluster Era",
            done() { return player.or11.unlocked },
            tooltip: "Enter the Cluster Era (row 11).<br>Reward: passive generation granted",
            effect() { return new Decimal(1) },
        },
        39: { name: "Cosmic Era",
            done() { return player.or16.unlocked },
            tooltip: "Enter the Cosmic Era (row 16).<br>Reward: auto-upgrades granted",
            effect() { return new Decimal(1) },
        },
        40: { name: "The Home Galaxy",
            done() { return player.mw.unlocked },
            tooltip: "Assemble The Milky Way.<br>Reward: stardust ×100",
            effect() { return new Decimal(100) },
        },
        41: { name: "Wind Walker",
            done() { return player.mw.winding.gte(16) },
            tooltip: "Wind the arms to a ×16 stack.<br>Reward: stardust ×50",
            effect() { return new Decimal(50) },
        },
        42: { name: "Local Boy",
            done() { return player.lg.unlocked },
            tooltip: "Bind The Local Group.<br>Reward: stardust ×100",
            effect() { return new Decimal(100) },
        },
        43: { name: "Virgo Pilgrim",
            done() { return player.vc.unlocked },
            tooltip: "Reach The Virgo Cluster.<br>Reward: stardust ×100",
            effect() { return new Decimal(100) },
        },
        44: { name: "Laniakea Bound",
            done() { return player.ln.unlocked },
            tooltip: "Flow into Laniakea.<br>Reward: stardust ×100",
            effect() { return new Decimal(100) },
        },
        45: { name: "Web Weaver",
            done() { return player.cw.unlocked },
            tooltip: "Thread The Cosmic Web.<br>Reward: stardust ×100",
            effect() { return new Decimal(100) },
        },
        46: { name: "Attractor's Pull",
            done() { return player.ga.unlocked },
            tooltip: "Feel The Great Attractor.<br>Reward: stardust ×100",
            effect() { return new Decimal(100) },
        },
        47: { name: "Space Pushes Back",
            done() { return player.de.unlocked },
            tooltip: "Awaken Dark Energy.<br>Reward: stardust ×100",
            effect() { return new Decimal(100) },
        },
        48: { name: "Edge of Light",
            done() { return player.hr.unlocked },
            tooltip: "Touch The Cosmic Horizon.<br>Reward: stardust ×1000",
            effect() { return new Decimal(1000) },
        },
        49: { name: "Upscaler",
            done() { return player.dm.upgrades.length >= 4 },
            tooltip: "Buy 4 Singularity Bazaar upgrades.<br>Reward: stardust ×50",
            effect() { return new Decimal(50) },
        },
        50: { name: "Deep Time",
            done() { return player.timePlayed >= 3600 },
            tooltip: "Play for one hour.<br>Reward: stardust ×10",
            effect() { return new Decimal(10) },
        },
        51: { name: "Marathoner",
            done() { return player.timePlayed >= 14400 },
            tooltip: "Play for four hours.<br>Reward: stardust ×25",
            effect() { return new Decimal(25) },
        },
        52: { name: "Automation Nation",
            done() { return hasMilestone("sg18", 2) },
            tooltip: "Unlock the Cosmic Era package deal.<br>Reward: bragging rights",
            effect() { return new Decimal(1) },
        },
        53: { name: "Hard Reset Refuser",
            done() { return player.gc.best.gte("1e10") },
            tooltip: "Hold 1e10 gas clouds best.<br>Reward: stardust ×100",
            effect() { return new Decimal(100) },
        },
        54: { name: "Light Collector",
            done() { return player.hr.total.gte(5) },
            tooltip: "Gather 5 light-years.<br>Reward: stardust ×100",
            effect() { return new Decimal(100) },
        },
        55: { name: "Lattice Watcher",
            done() { return player.or5.best.gte(1.44) && hasUpgrade("or5", 14) },
            tooltip: "Crystallize a white dwarf core at the limit.<br>Reward: stardust ×50",
            effect() { return new Decimal(50) },
        },
        56: { name: "Maser Chorus",
            done() { return hasUpgrade("pe17", 25) && hasUpgrade("pe18", 25) },
            tooltip: "Open both maser shops.<br>Reward: stardust ×50",
            effect() { return new Decimal(50) },
        },
        57: { name: "Jet Setter",
            done() { return hasUpgrade("oa14", 25) },
            tooltip: "Open the Relativistic Jets shop.<br>Reward: stardust ×50",
            effect() { return new Decimal(50) },
        },
        58: { name: "Filament Follower",
            done() { return hasUpgrade("sg21", 25) },
            tooltip: "Walk the Dark Matter Filaments.<br>Reward: stardust ×50",
            effect() { return new Decimal(50) },
        },
        59: { name: "Stardust Billionaire",
            done() { return player.points.gte("1e12") },
            tooltip: "Hold 1e12 stardust.<br>Reward: stardust ×25",
            effect() { return new Decimal(25) },
        },
        60: { name: "Deca-Trialist",
            done() { return challengeCompletions("oa6", 11) + challengeCompletions("oa6", 12) >= 6 },
            tooltip: "Six total Trial completions.<br>Reward: stardust ×50",
            effect() { return new Decimal(50) },
        },
        61: { name: "Nebula Nostalgist",
            done() { return hasUpgrade("gc", 31) },
            tooltip: "Finish the Gas Clouds upgrade grid.<br>Reward: bragging rights",
            effect() { return new Decimal(1) },
        },
        62: { name: "Full Ignition",
            done() { return hasUpgrade("ps", 23) },
            tooltip: "Finish the Protostar upgrade set.<br>Reward: bragging rights",
            effect() { return new Decimal(1) },
        },
        63: { name: "Reactor Baron",
            done() { return getBuyableAmount("fu", 11).gte(25) },
            tooltip: "Buy 25 Confinement Torus levels.<br>Reward: stardust ×50",
            effect() { return new Decimal(50) },
        },
        64: { name: "Perseid",
            done() { return player.pe5.unlocked },
            tooltip: "Reach row 5 of the Perseus Arm.<br>Reward: stardust ×25",
            effect() { return new Decimal(25) },
        },
        65: { name: "Sagittarian",
            done() { return player.sg5.unlocked },
            tooltip: "Reach row 5 of the Sagittarius Arm.<br>Reward: stardust ×25",
            effect() { return new Decimal(25) },
        },
        66: { name: "Orionid",
            done() { return player.or5.unlocked },
            tooltip: "Reach row 5 of the Orion Arm.<br>Reward: stardust ×25",
            effect() { return new Decimal(25) },
        },
        67: { name: "Outburst",
            done() { return player.oa5.unlocked },
            tooltip: "Reach row 5 of the Outer Arm.<br>Reward: stardust ×25",
            effect() { return new Decimal(25) },
        },
        68: { name: "The Long Zoom",
            done() { return player.hr.total.gte(12) },
            tooltip: "Gather 12 light-years.<br>Reward: stardust ×500",
            effect() { return new Decimal(500) },
        },
        69: { name: "You Are Here",
            done() { return player.hr.total.gte(25) },
            tooltip: "Beat the game. The pale blue dot thanks you.<br>Reward: bragging rights",
            effect() { return new Decimal(1) },
        },
    },
})

addLayer("s", {
    name: "The Observatory",
    startData() { return { unlocked: true, points: new Decimal(0) } },
    color: "#a5d6a7",
    row: "side",
    symbol: "S",
    tooltip() { return "Observatory statistics" },
    type: "none",
    tabFormat: [
        ["display-text", function() { return 'Time played: <b>' + formatTime(player.timePlayed) + '</b>' }],
        ["display-text", function() { return 'Stardust: <b>' + format(player.points) + '</b>' }],
        ["display-text", function() { return 'Gas clouds best: ' + format(player.gc.best) + ' — fusion plasma best: ' + format(player.fu.best) }],
        ["display-text", function() { return 'Planetary systems best: ' + format(player.pl.best) + ' — protostar ignitions: ' + formatWhole(player.ps.ignitions) }],
        ["display-text", function() { return 'Heavy elements: ' + format(player.or7.heavy) + ' — dark matter: ' + format(player.dm.darkMatter) }],
        ["display-text", function() { return 'Light-years gathered: ' + formatWhole(player.hr.total) }],
        ["display-text", function() { return 'Survey badges earned: ' + formatWhole(player.a.achievements.length) + ' / 60' }],
        ["display-text", function() { return 'Trial records: ' + player.oa6.maxpoints.map(mp => formatWhole(mp)).join(', ') }],
    ],
})

addLayer("ch", {
    name: "The Chronicle",
    startData() { return { unlocked: true, points: new Decimal(0) } },
    color: "#ce93d8",
    row: "side",
    symbol: "CH",
    tooltip() { return "The Chronicle" },
    type: "none",
    tabFormat: [
        ["infobox", "c1"], ["infobox", "c2"], ["infobox", "c3"], ["infobox", "c4"], ["infobox", "c5"],
        ["infobox", "c6"], ["infobox", "c7"], ["infobox", "c8"], ["infobox", "c9"], ["infobox", "c10"],
    ],
    infoboxes: {
        c1: { title: "I. A Grain of Dust", body() { return hasMilestone("gc", 0) ? "It began with a grain of stardust — colder than space, older than the sun. Gravity did the rest." : "???" } },
        c2: { title: "II. First Light", body() { return player.ps.ignitions >= 3 ? "The core held its breath, then burned. A star existed where nothing had." : "???" } },
        c3: { title: "III. The Four Arms", body() { return player.oa1.unlocked ? "Four great arms spiral outward from the fire — each one a history waiting to be written." : "???" } },
        c4: { title: "IV. Life and Death of Suns", body() { return player.or7.unlocked ? "Stars are the universe's alchemists. They burn hydrogen, forge iron, and die so that worlds may form." : "???" } },
        c5: { title: "V. The Dark Ledger", body() { return player.sg10.unlocked ? "Most of the galaxy is missing. It does not glow, it does not speak — it simply pulls." : "???" } },
        c6: { title: "VI. The Grand Assembly", body() { return player.mw.unlocked ? "Two hundred billion suns, one barred spiral. The Milky Way is not a place. It is a verb." : "???" } },
        c7: { title: "VII. The Neighbors", body() { return player.lg.unlocked ? "Andromeda is falling toward us. In four billion years, the Local Group will be one." : "???" } },
        c8: { title: "VIII. The Deep Field", body() { return player.vc.unlocked ? "Beyond the group: clusters, superclusters, filaments — galaxies tracing the skeleton of everything." : "???" } },
        c9: { title: "IX. The Acceleration", body() { return player.de.unlocked ? "The expansion is speeding up. Space itself has learned to push, and nothing is holding it back." : "???" } },
        c10: { title: "X. The Horizon", body() { return player.hr.unlocked ? "There is a line no light has crossed. You have gathered everything up to it. Beyond — silence, and more universe." : "???" } },
    },
})

addLayer("dm", {
    name: "The Singularity Bazaar",
    startData() { return { unlocked: true, points: new Decimal(0), darkMatter: new Decimal(0) } },
    color: "#90a4ae",
    row: "side",
    symbol: "DM",
    tooltip() { return "Spend dark matter on reality-bending upgrades" },
    type: "none",
    tabFormat: [
        ["display-text", function() { return 'You have <b style="color:#b388ff">' + format(player.dm.darkMatter) + '</b> dark matter (produced by the Dark Matter Halo)' }],
        ["blank", "12px"],
        "upgrades",
    ],
    upgrades: {
        11: { title: "Halo Amplifier",
              description: "Dark matter production ×2.",
              cost: new Decimal(10),
              currencyDisplayName: "dark matter",
              currencyInternalName: "darkMatter",
              currencyLocation() { return player.dm } },
        12: { title: "Vacuum Distilled",
              description: "Stardust gain ×1e3.",
              cost: new Decimal(100),
              currencyDisplayName: "dark matter",
              currencyInternalName: "darkMatter",
              currencyLocation() { return player.dm } },
        13: { title: "Density Wave Overdrive",
              description: "Every normal arm lane's gain multiplier is raised to ^1.03.",
              cost: new Decimal(1e4),
              currencyDisplayName: "dark matter",
              currencyInternalName: "darkMatter",
              currencyLocation() { return player.dm } },
        14: { title: "Cloud Cataclysm",
              description: "Gas cloud gain ×1e4.",
              cost: new Decimal(1e5),
              currencyDisplayName: "dark matter",
              currencyInternalName: "darkMatter",
              currencyLocation() { return player.dm } },
        15: { title: "Supernova Foundry",
              description: "Heavy element production ×3.",
              cost: new Decimal(1e6),
              currencyDisplayName: "dark matter",
              currencyInternalName: "darkMatter",
              currencyLocation() { return player.dm } },
        21: { title: "Cosmic Ledger",
              description: "Stardust gain ×1e5.",
              cost: new Decimal(1e8),
              currencyDisplayName: "dark matter",
              currencyInternalName: "darkMatter",
              currencyLocation() { return player.dm } },
        22: { title: "Quintessence Contract",
              description: "Vacuum energy gain ×10.",
              cost: new Decimal(1e10),
              currencyDisplayName: "dark matter",
              currencyInternalName: "darkMatter",
              currencyLocation() { return player.dm } },
        23: { title: "Dark Scaffold",
              description: "All four arm lanes gain ×1e6.",
              cost: new Decimal(1e12),
              currencyDisplayName: "dark matter",
              currencyInternalName: "darkMatter",
              currencyLocation() { return player.dm } },
    },
})
